name: Xamarin

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:

    Build_Android:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1
        
      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install Boots
        run : |
          dotnet tool install --global boots --prerelease
          boots --alpha Mono
          boots --alpha Xamarin.Android
        
      - name: Restore NuGet 
        run: |
          nuget restore
          
      - name: Build Android App
        run: |                    
          msbuild ./DarkModeSplashScreen.Android/DarkModeSplashScreen.Android.csproj /verbosity:normal /p:Configuration=Release     
